name: Deploy to AWS via Serverless Framework

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # To access repo contents
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless@4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::664418970006:role/GitHubOIDCRole 
          aws-region: us-east-1

      - name: Deploy to AWS
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          export SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}
          npx serverless deploy --verbose

